In [1]:
import pandas as pd
import numpy as np
import os 

In [2]:
# get the path of the precessed data
processed_data_path = os.path.join(os.path.pardir,'data','processed')
train_file_path = os.path.join(processed_data_path,'train.csv')
test_file_path = os.path.join(processed_data_path,'test.csv')

In [3]:
train_df= pd.read_csv(train_file_path,index_col= 'PassengerId')
test_df = pd.read_csv(test_file_path,index_col = 'PassengerId')

In [4]:
train_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 891 entries, 1 to 891
Data columns (total 34 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Survived            891 non-null    int64  
 1   Age                 891 non-null    float64
 2   Fare                891 non-null    float64
 3   FamilySize          891 non-null    int64  
 4   Ismother            891 non-null    int64  
 5   ismale              891 non-null    int64  
 6   deck_A              891 non-null    int64  
 7   deck_B              891 non-null    int64  
 8   deck_C              891 non-null    int64  
 9   deck_D              891 non-null    int64  
 10  deck_E              891 non-null    int64  
 11  deck_F              891 non-null    int64  
 12  deck_G              891 non-null    int64  
 13  deck_Z              891 non-null    int64  
 14  Pclass_1            891 non-null    int64  
 15  Pclass_2            891 non-null    int64  
 16  Pclass_3

In [5]:
test_df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 418 entries, 892 to 1309
Data columns (total 33 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   Age                 418 non-null    float64
 1   Fare                418 non-null    float64
 2   FamilySize          418 non-null    int64  
 3   Ismother            418 non-null    int64  
 4   ismale              418 non-null    int64  
 5   deck_A              418 non-null    int64  
 6   deck_B              418 non-null    int64  
 7   deck_C              418 non-null    int64  
 8   deck_D              418 non-null    int64  
 9   deck_E              418 non-null    int64  
 10  deck_F              418 non-null    int64  
 11  deck_G              418 non-null    int64  
 12  deck_Z              418 non-null    int64  
 13  Pclass_1            418 non-null    int64  
 14  Pclass_2            418 non-null    int64  
 15  Pclass_3            418 non-null    int64  
 16  Title

In [6]:
test_df.head(10)

Age     Fare  FamilySize  Ismother  ismale  deck_A  deck_B  \
PassengerId                                                                
892          34.5   7.8292           1         0       0       0       0   
893          47.0   7.0000           2         0       0       0       0   
894          62.0   9.6875           1         0       0       0       0   
895          27.0   8.6625           1         0       0       0       0   
896          22.0  12.2875           3         0       0       0       0   
897          14.0   9.2250           1         0       0       0       0   
898          30.0   7.6292           1         0       0       0       0   
899          26.0  29.0000           3         0       0       0       0   
900          18.0   7.2292           1         0       0       0       0   
901          21.0  24.1500           3         0       0       0       0   

             deck_C  deck_D  deck_E  ...  Title_mrs  Fare_bin_very_low  \
PassengerId                          ...                                 
892               0       0       0  ...          0                  1   
893               0       0       0  ...          1                  1   
894               0       0       0  ...          0                  0   
895               0       0       0  ...          0                  0   
896               0       0       0  ...          1                  0   
897               0       0       0  ...          0                  0   
898               0       0       0  ...          0                  1   
899               0       0       0  ...          0                  0   
900               0       0       0  ...          1                  1   
901               0       0       0  ...          0                  0   

             Fare_bin_low  Fare_bin_high  Fare_bin_very_high  Embarked_C  \
PassengerId                                                                
892                     0              0                   0           0   
893                     0              0                   0           0   
894                     1              0                   0           0   
895                     1              0                   0           0   
896                     1              0                   0           0   
897                     1              0                   0           0   
898                     0              0                   0           0   
899                     0              1                   0           0   
900                     0              0                   0           1   
901                     0              1                   0           0   

             Embarked_Q  Embarked_S  AgeState_Adult  AgeState_Child  
PassengerId                                                          
892                   1           0               1               0  
893                   0           1               1               0  
894                   1           0               1               0  
895                   0           1               1               0  
896                   0           1               1               0  
897                   0           1               0               1  
898                   1           0               1               0  
899                   0           1               1               0  
900                   0           0               1               0  
901                   0           1               1               0  

[10 rows x 33 columns]

# Data preperation

In [7]:
X = train_df.loc[:,"Age":].to_numpy() .astype('float')
y = train_df['Survived'].ravel()

In [8]:
print(X.shape, y.shape)

(891, 33) (891,)


In [9]:
# train split test
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X ,y, test_size=0.2, random_state=0)
print(X_train.shape, y_train.shape)
print(X_test.shape,y_test.shape)

(712, 33) (712,)
(179, 33) (179,)


In [10]:
print('mean survival in train : {0: .3f}'.format(np.mean(y_train)))
print('mean survival in test : {0: .3f}'.format(np.mean(y_test)))

mean survival in train :  0.383
mean survival in test :  0.385


In [11]:
import sklearn

In [12]:
sklearn.__version__

'0.22.1'

In [13]:
from sklearn.dummy import DummyClassifier 

In [14]:
#create model
Model_dummy = DummyClassifier(strategy = 'most_frequent' ,random_state =0)

In [15]:
# train model 
Model_dummy.fit(X_train, y_train)

DummyClassifier(constant=None, random_state=0, strategy='most_frequent')

In [16]:
print('score for basemodel : {0: 0.2f}'.format(Model_dummy.score(X_test ,y_test)))

score for basemodel :  0.61


In [17]:
# performance matrix
from sklearn.metrics import accuracy_score, confusion_matrix, precision_score, recall_score 

In [18]:
#accuracy score
print('Accuracy score for baseline : {0: 0.2f}'.format(accuracy_score(y_test,Model_dummy.predict(X_test))))

Accuracy score for baseline :  0.61


In [19]:
print('confusion matrix for baseline model: \n {0}'.format(confusion_matrix(y_test, Model_dummy.predict(X_test))))

confusion matrix for baseline model: 
 [[110   0]
 [ 69   0]]


In [20]:
print('precision for baseline model: {0:.2f}'.format(precision_score(y_test, Model_dummy.predict(X_test))))
print('recall for baseline model \n {0}'.format(recall_score(y_test, Model_dummy.predict(X_test))))

precision for baseline model: 0.00
recall for baseline model 
 0.0


C:\ProgramData\Anaconda3\lib\site-packages\sklearn\metrics\_classification.py:1272: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 due to no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))


# first kaggle Submission

In [21]:
# Conveting to the matirix
test_X = test_df.to_numpy() .astype('float')

In [22]:
# get prediction
predictions = Model_dummy.predict(test_X)

In [23]:
df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived':predictions})

In [24]:
df_submission.head()

PassengerId  Survived
0          892         0
1          893         0
2          894         0
3          895         0
4          896         0

In [25]:
submission_data_path = os.path.join(os.path.pardir,'data','external')
submission_file_path = os.path.join(submission_data_path, 'frist_prediction.csv')

In [26]:
df_submission.to_csv(submission_file_path,index = False)

In [27]:
# writing function for submission of prediction

def get_submission_file(model ,filename):
    #converting to matrix
    test_X = test_df.to_numpy() .astype('float')
    #make prediction
    predictions = model.predict(test_X)
    #submision dataframe
    df_submission = pd.DataFrame({'PassengerId': test_df.index, 'Survived':predictions})
    # submit file
    submission_data_path = os.path.join(os.path.pardir,'data','external')
    submission_file_path = os.path.join(submission_data_path, filename)
    # write to file
    df_submission.to_csv(submission_file_path, index = False)
    
    

In [28]:
#get submission file
get_submission_file(Model_dummy, 'frist_prediction.csv')

# logistic Regression Model

In [29]:
from sklearn.linear_model import LogisticRegression

In [30]:
# creating model
model_logicRegre = LogisticRegression(random_state=0)

In [31]:
model_logicRegre.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)


LogisticRegression(C=1.0, class_weight=None, dual=False, fit_intercept=True,
                   intercept_scaling=1, l1_ratio=None, max_iter=100,
                   multi_class='auto', n_jobs=None, penalty='l2',
                   random_state=0, solver='lbfgs', tol=0.0001, verbose=0,
                   warm_start=False)

In [32]:
#evaluate model
print('score the logicRegre version 1 : {0:.2f} '.format(model_logicRegre.score(X_test, y_test)))

score the logicRegre version 1 : 0.83 


In [33]:
print('confusion matrix for model_logicRegre: \n {0}'.format(confusion_matrix(y_test, model_logicRegre.predict(X_test))))

confusion matrix for model_logicRegre: 
 [[94 16]
 [15 54]]


In [34]:
print('precision for model_logicRegre: {0:.2f}'.format(precision_score(y_test, model_logicRegre.predict(X_test))))
print('recall for model_logicRegre \n {0:.2f}'.format(recall_score(y_test, model_logicRegre.predict(X_test))))

precision for model_logicRegre: 0.77
recall for model_logicRegre 
 0.78


In [35]:
model_logicRegre.coef_

array([[-0.03104926,  0.0039438 , -0.47040405,  0.        ,  0.        ,
         0.07961421, -0.0976519 , -0.41472212,  0.47813974,  1.06473866,
         0.24691929, -0.03654361, -0.40803724,  0.84137233,  0.46897633,
        -0.39789165,  0.14388065,  0.71946645,  0.82689047, -1.92233487,
         0.15767629, -0.29253059, -0.34810733,  1.62751594,  0.09380378,
         0.19966185,  0.22809409,  0.3908973 ,  0.39644946,  0.42493207,
         0.09107549,  0.32746163,  0.58499539]])

In [36]:
#Submission on Logistic regression
get_submission_file(model_logicRegre, 'logicRegression_predict.csv')

# HypterparameterOptimisation

In [37]:
model_logicRegre= LogisticRegression(random_state=0)

In [38]:
from sklearn.model_selection import GridSearchCV 

In [43]:
parameters = {'C':[1.0,10.0,50.0,1000.0],'penalty' : ['l1','l2']}
clf = GridSearchCV(model_logicRegre,param_grid = parameters,cv =3)

In [44]:
clf.fit(X_train, y_train)

C:\ProgramData\Anaconda3\lib\site-packages\sklearn\model_selection\_validation.py:536: FitFailedWarning: Estimator fit failed. The score on this train-test partition for these parameters will be set to nan. Details: 
ValueError: Solver lbfgs supports only 'l2' or 'none' penalties, got l1 penalty.

  FitFailedWarning)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  extra_warning_msg=_LOGISTIC_SOLVER_CONVERGENCE_MSG)
C:\ProgramData\Anaconda3\lib\site-packages\sklearn\linear_model\_logistic.py:940: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL

GridSearchCV(cv=3, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight=None, dual=False,
                                          fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=0, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1.0, 10.0, 50.0, 1000.0],
                         'penalty': ['l1', 'l2']},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring=None, verbose=0)

In [45]:
clf.best_params_

{'C': 1.0, 'penalty': 'l2'}

In [46]:
print('best score : {0:.2f}'.format(clf.best_score_))

best score : 0.83


In [48]:
print('score for logiistic regression V 2 : {0:0.2f}'.format(clf.score(X_test, y_test)))

score for logiistic regression V 2 : 0.83


In [50]:
get_submission_file(clf, 'predict_3.csv')